name: flutter_compass_v2
description: A Flutter compass. The heading varies from 0-360, 0 being north.
version: 1.0.0
homepage: https://github.com/medyas/flutter_compass_v2

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.10.0'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.hemanthraj.fluttercompass
        pluginClass: FlutterCompassPlugin
      ios:
        pluginClass: FlutterCompassPlugin
